void textSize(int a,int b);
void changepos(int a,int b);
void Cycle(char user[]);
void showCycle(char user []);
void Buckets();
void showBuckets();
void Electronics();
void showElectronics();
void Matress();
void showMatress();
void Laptops();
void showLaptops();
void sell(char user[]);
void purchase(char user[]);
void del(char user[]);
void main_menu(char user[]);
void login();
void createAccount();
void forgot();
//int main();

